version: '3'
services:
  monero:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monero
    restart: always
    volumes:
      - ../monero:/home/monero/.bitmonero
    network_mode: host
    command: ./monerod --data-dir /home/monero/.bitmonero --stagenet --non-interactive --rpc-bind-ip=0.0.0.0 --confirm-external-bind
  monero-wallet-rpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monero-wallet-rpc
    restart: always
    volumes:
      - ../monero:/home/monero/.bitmonero
    network_mode: host
    command: ./monero-wallet-rpc --wallet-dir /home/monero/.bitmonero --stagenet --rpc-bind-port=38083 --rpc-bind-ip=0.0.0.0 --rpc-login=rpc_user:rpc_pass --daemon-address=http://localhost:38081 --confirm-external-bind
    # if you want to connect to external daemon use this command
    # command: ./monero-wallet-rpc --wallet-dir /home/monero/.bitmonero --stagenet --rpc-bind-port=38083 --rpc-bind-ip=0.0.0.0 --rpc-login=rpc_user:rpc_pass --daemon-address=http://stagenet.xmr-tw.org:38081 --confirm-external-bind
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node
    environment:
      - MONGO_URI=mongodb://mongo:27017/escrow
    restart: always
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ../uploads:/uploads
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - ../mongo:/data/db
    ports:
      - 27017:27017


  
